# ===================
# MySQL
#====================

default: &default
  adapter: mysql2
  encoding: utf8
  # host: db
  host: 127.0.0.1
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: conversor_development

test:
  <<: *default
  database: conversor_test

production:
  <<: *default
  database: conversor_production
